<?php
//Refer to the existing session
session_start();
if (!isset($_SESSION['authenticated']) || !$_SESSION['authenticated']) {
    header('Location: index.php');
    exit();
}

//Declare variables
$numberOfProvinces = 10;
$numberOfTerritories = 3;
$motto = ["A mari usque ad mare (Latin)", "From Sea to Sea (English)", "De mer en mer (Français)"];
$anthem = "O Canada";
$capital = "Ottawa";
$largestCity ="Toronto";
$officialLanguages = ["English", "French"];
$governmentType = "Federal parliamentary constitutional monarchy";
$totalArea = 9984670;
$percentWaterArea = 11.76;
$population = 40528396;
$currency = 'Canadian dollar ($CA)';
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Canadian Provinces & Territories</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <header>
            <h1 class="canada-info-title1">Information about Canada and state</h1>
            <div class="user-info">
                Thank you for your interest in Canada <?php echo $_SESSION['username']; ?>! 
                <a href="logout.php" class="btn logout">Logout</a>
            </div>
            <h2 class="canada-info-title2">Information about Canada</h2>
            <div class="info-grid">
                <div class="canada-flag">
                    <p><b>Flag|Drapeau</b></p>
                    <img class="" src="media/Flag_of_Canada_(Pantone).svg.png.webp"/>
                    <p><b>Coat of arms|Armoiries</b></p>
                    <img class="" src="media/Coat_of_arms_of_Canada.svg.png.webp"/> 
                </div>
                <div class="canada-info">
                    <p class="display-outputs"><strong>Number of Provinces|Nombre de Provinces:</strong><span class="label"><?php echo $numberOfProvinces ?></span></p>
                    <p class="display-outputs"><strong>Number of Territories|Nombre de Territoires:</strong><span class="label"><?php echo $numberOfTerritories ?></span></p>
                    <p class="display-outputs"><strong>Motto|Slogan:</strong><span class="label"><?php echo implode(separator: '<br>', array: $motto); ?></span></p>
                    <p class="display-outputs"><strong>Anthem|Hymne:</strong><span class="label"><?php echo $anthem ?></span></p>
                    <p class="display-outputs"><strong>Capital|Capitale:</strong><span class="label"><?php echo $capital ?></span></p>
                    <p class="display-outputs"><strong>Largest city|Plus grande ville:</strong><span class="label"><?php echo $largestCity ?></span></p>
                </div>
                <div class="canada-info">
                    <p class="display-outputs"><strong>Official languages|Langues officielles:</strong><span class="label"><?php echo implode(separator: '<br>', array: $officialLanguages); ?></span></p>
                    <p class="display-outputs"><strong>Government type|Type de gouvernement:</strong><span class="label"><?php echo $governmentType ?></span></p>
                    <p class="display-outputs"><strong>Total area|Superficie totale:</strong><span class="label"><?php echo $totalArea; ?></span></p>
                    <p class="display-outputs"><strong>Percent Water Area|Pourcentage de la superficie en eau :</strong><span class="label"><?php echo $percentWaterArea ?></span></p>
                    <p class="display-outputs"><strong>Population|Population:</strong><span class="label"><?php echo $population ?></span></p>
                    <p class="display-outputs"><strong>$currency|Monnaie:</strong><span class="label"><?php echo $currency ?></span></p>
                </div>
            </div>
        </header>
        
        <div class="image-map">
            <h2 class="canada-info-title2">Information about a Province or Territory</h2>
            <h3>Select first to display the information next</h3>
            <!-- Image Map Generated by http://www.image-map.net/ -->
            <img src="media/1024px-Canada_political_map_-_en.svg.png" usemap="#image-map">
            <map name="image-map">
                <area target="_self" alt="Yukon" title="Yukon" coords="50,327,149,211,164,225,141,258,159,271,153,284,153,296,147,308,146,322,148,335,148,349,146,361,143,376,147,389,147,407,166,417,160,420,56,355" shape="poly" href="one_place_result.php?name=Yukon">
                <area target="_self" alt="British Columbia" title="British Columbia" coords="91,636,194,675,154,569,196,452,76,381,75,447,85,470,60,500,59,551,60,576" shape="poly" href="one_place_result.php?name=British Columbia">
                <area target="_self" alt="Alberta" title="Alberta" coords="209,457,167,567,207,670,244,688,296,486" shape="poly" href="one_place_result.php?name=Alberta">
                <area target="_self" alt="Saskatshewan" title="Saskashewan" coords="305,487,372,497,361,707,255,690" shape="poly" href="one_place_result.php?name=Saskashewan">
                <area target="_self" alt="Manitoba" title="Manitoba" coords="385,499,370,708,445,716,443,641,508,561,495,556,484,563,474,567,466,530,445,525,446,503" shape="poly" href="one_place_result.php?name=Manitoba">
                <area target="_self" alt="Ontario" title="Ontario" coords="516,563,526,575,550,581,567,590,590,586,593,603,598,621,605,634,615,645,639,659,649,692,657,720,668,737,675,747,693,752,711,752,728,754,738,753,725,771,705,779,687,786,679,802,677,810,667,819,654,825,657,810,657,795,668,790,678,780,674,764,655,758,634,753,613,752,601,744,585,724,572,710,551,704,532,712,519,725,499,729,479,721,462,716,456,704,451,680,452,640" shape="poly" href="one_place_result.php?name=Ontario">
                <area target="_self" alt="Quebec" title="Quebec" coords="615,431,631,470,627,494,649,516,658,540,653,558,641,574,646,598,659,634,652,654,676,730,720,742,750,734,768,736,785,726,791,709,773,697,782,677,782,654,799,622,813,595,858,578,881,559,892,532,865,546,842,560,817,575,794,577,776,578,761,566,755,550,753,530,756,516,770,508,782,506,775,490,767,476,751,448,740,466,726,479,711,482,696,460,689,442,666,431,651,422" shape="poly" href="one_place_result.php?name=Quebec">
                <area target="_self" alt="New Brunswick" title="New Brunswick" coords="819,666,845,704,870,678,858,665,847,666,850,655,837,655" shape="poly" href="one_place_result.php?name=New Brunswick">
                <area target="_self" alt="Nova Scotia" title="Nova Scotia" coords="871,713,894,677,914,666,913,676,895,695,886,706,883,718,879,725,871,721" shape="poly" href="one_place_result.php?name=Nova Scotia">
                <area target="_self" alt="New Foundland and Labrador" title="New Foundland and Labrador" coords="752,433,791,488,806,516,787,525,772,532,770,544,783,555,795,560,807,567,815,563,833,554,852,544,875,527,889,514,899,519,911,526,914,539,913,560,919,576,921,591,925,605,938,593,951,582,966,576,975,560,966,553,960,544,955,553,944,552,935,555,925,555,919,545,918,532,911,520,908,512,899,504,891,495,875,490,864,497,855,513,849,518,839,519,841,508,848,497,857,485,845,486,828,488,815,484,806,480,796,471,789,460" shape="poly" href="one_place_result.php?name=New Foundland and Labrador">
                <area target="_self" alt="Northwest Territories" title="Northwest Territories" coords="182,218,160,254,171,264,165,284,167,300,158,315,160,400,179,409,179,432,292,476,379,487,387,414,328,393,320,376,303,370,259,300,277,261,345,280,394,88,316,135,234,261,243,225,228,216,207,220,195,219" shape="poly" href="one_place_result.php?name=Northwest Territories">
                <area target="_self" alt="Nunavut" title="Nunavut" coords="278,281,268,302,309,366,325,367,333,384,389,407,383,490,450,492,459,463,472,442,482,430,439,416,437,403,487,422,498,408,705,398,707,296,548,205,540,17,496,28,445,78,407,127,383,172,377,226,363,260,349,296,976,306" shape="poly" href="one_place_result.php?name=Nunavut">
            </map>      
        </div>
    </div>
</body>
</html>